### ISSUE TITLE
Урок "JavaScript: Синтаксические ошибки" - неверная ссылка

### ISSUE THREAD

**Issue by it4joy** [hexlet-basics/exercises-pre-course-javascript#2]
В абзаце:

> По техническим причинам, такой код, запущенный на https://code-basics.com/ не укажет на строку и файл. Проверить этот вывод можно на https://repl.it/

Ссылка на Replit здесь указана неверная, нужно https://replit.com. Да, перенаправление есть, но для единства, может, лучше использовать этот адрес (ниже указанного абзаца приводится ссылка вида https://replit.com/@hexlet/js-basics-syntax-errors).

**Comment by aloescript** [comment]
@it4joy тут тоже, оформите, пжлста, предлагаемые изменения в виде pull request
